assert {[have_board imx8mp_armstone]}

create_boot_directory

import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/src/init \
                  [depot_user]/raw/[board]-devices

set build_components {
	driver/framebuffer/armstone
	driver/platform/imx8mp
	driver/pin/imx
	test/framebuffer
}

build $build_components

install_config {
config | verbose: yes
+ parent-provides
  + service ROM
  + service IRQ
  + service IO_MEM
  + service IO_PORT
  + service PD
  + service RM
  + service CPU
  + service LOG

+ default-route
  + any-service
    + parent
    + any-child

+ default | caps: 100

+ start timer
  + resource RAM | quantum: 1M
  + provides | + service Timer

+ start platform | caps: 150 | managing_system: yes
  + binary imx8mp_platform
  + resource RAM | quantum: 1M
  + provides | + service Platform
  + route | + any-service | + parent
  + config
    + policy | label: fb ->  | info: yes
      + device hdmimix_pd
      + device hdmi_pd
      + device hdmi
      + device hdmi_pavi
      + device hdmi_phy
      + device hdmi_blk_ctrl
      + device irqsteer
      + device lcdif3
      + device pwm3
    + policy | label: gpio ->  | info: yes
      + device gpio1
      + device gpio2
      + device gpio3
      + device gpio4
      + device gpio5

+ start gpio | caps: 150
  + binary imx_pio
  + resource RAM | quantum: 2M
  + provides
    + service Pin_state
    + service Pin_control
    + service IRQ
  + config
    + out backlight | index: 28 | bank: 3 | default: on
  + route
    + service RM       | + parent
    + service ROM      | + parent
    + service PD       | + parent
    + service CPU      | + parent
    + service LOG      | + parent
    + service Platform | + child platform

+ start fb | caps: 250
  + binary imx8mp_armstone_fb
  + resource RAM | quantum: 128M
  + route
    + service ROM | label: dtb | + parent | label: imx8mp_armstone_fb-imx8mp_armstone.dtb
    + service RM               | + parent
    + service ROM              | + parent
    + service PD               | + parent
    + service CPU              | + parent
    + service LOG              | + parent
    + service Timer            | + child timer
    + service Platform         | + child platform
    + service Capture          | + child test-framebuffer

+ start test-framebuffer
  + resource RAM | quantum: 10M
  + provides | + service Capture
  + config
-
}

set fd [open [run_dir]/genode/system w]
puts $fd "system | state:\n-"
close $fd

build_boot_image [build_artifacts]

run_genode_until forever
