assert {[have_spec arm_v8a]}

create_boot_directory

import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/src/init \
                  [depot_user]/src/imx8mq_fb \
                  [depot_user]/raw/[board]-devices

set build_components {
	driver/framebuffer/imx8mq
	driver/platform/imx8mq
	test/framebuffer
}

append_if [have_board mnt_reform2] build_components {
	driver/pin/imx
	driver/i2c/imx8q_evk
	driver/pwm/imx8mq
}

build $build_components

set config {
config
+ parent-provides
  + service ROM
  + service IRQ
  + service IO_MEM
  + service IO_PORT
  + service PD
  + service RM
  + service CPU
  + service LOG

+ default-route
  + any-service
    + parent
    + any-child

+ default | caps: 100 | ram: 1M

+ start timer
  + provides | + service Timer

+ start platform | caps: 150 | managing_system: yes
  + binary imx8mq_platform
  + provides | + service Platform
  + route | + any-service | + parent
  + config
    + policy | label: fb ->  | info: yes
      + device dcss
      + device hdmi
      + device irqsteer}
append_if [have_board mnt_reform2] config {
      + device mipi_dsi
      + device mipi_dsi_phy
      + device lcd
      + device pclk
      + device esc
      + device dpi
    + policy | label: imx8mq_pwm ->
      + device pwm
    + policy | label: gpio ->  | info: yes
      + device gpio1
      + device gpio2
      + device gpio3
      + device gpio4
      + device gpio5
    + policy | label: i2c ->
      + device i2c}

append config {
}

append_if [have_board mnt_reform2] config {
+ start gpio | caps: 150 | ram: 2M
  + binary imx_pio
  + provides
    + service Pin_state
    + service Pin_control
    + service IRQ
  + config
    + out backlight  | index: 10 | bank: 0 | default: on
    + out edp_bridge | index: 20 | bank: 2 | default: on
  + route
    + service RM       | + parent
    + service ROM      | + parent
    + service PD       | + parent
    + service CPU      | + parent
    + service LOG      | + parent
    + service Platform | + child platform

+ start i2c | caps: 150 | ram: 2M
  + binary imx8q_evk_i2c
  + provides | + service I2c
  + config | verbose: yes
    + policy | label_prefix: fb | bus_address: 0x2c
  + route
    + service RM       | + parent
    + service ROM      | + parent
    + service PD       | + parent
    + service CPU      | + parent
    + service LOG      | + parent
    + service Platform | + child platform
    + service Timer    | + child timer

+ start imx8mq_pwm | caps: 100 | ram: 2M
  + config | period: 248 | sample: 250 | clock_source: ipg_highfreq
  + route
    + service RM       | + parent
    + service ROM      | + parent
    + service PD       | + parent
    + service CPU      | + parent
    + service LOG      | + parent
    + service Platform | + child platform
}

append config {
+ start fb | caps: 250 | ram: 128M
  + binary imx8mq_fb
  + route
    + service ROM | label: dtb | + parent | label: } imx8mq_fb-[board].dtb {
    + service RM               | + parent
    + service ROM              | + parent
    + service PD               | + parent
    + service CPU              | + parent
    + service LOG              | + parent
    + service Timer            | + child timer
    + service Platform         | + child platform
    + service Capture          | + child test-framebuffer}
append_if [have_board mnt_reform2] config {
    + service I2c              | + child i2c}
append config {

+ start test-framebuffer | ram: 10M
  + provides | + service Capture
  + config
-
}

install_config $config

build_boot_image [build_artifacts]

run_genode_until forever
