assert {[have_board imx8q_evk]}

create_boot_directory

import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/src/init \
                  [depot_user]/src/imx8mq_platform \
                  [depot_user]/raw/imx8q_evk-devices

build { driver/i2c test/i2c_mcp9808 }

install_config {
config
+ parent-provides
  + service ROM
  + service IRQ
  + service IO_MEM
  + service PD
  + service RM
  + service CPU
  + service LOG

+ default-route
  + any-service
    + parent
    + any-child

+ default | caps: 100 | ram: 1M

+ start timer
  + provides | + service Timer

+ start platform | caps: 800 | ram: 4M | managing_system: yes
  + binary imx8mq_platform
  + provides | + service Platform
  + config
    + policy | label_prefix: imx8q_evk_i2c | + device i2c2

+ start imx8q_evk_i2c
  + provides | + service I2c
  + config | bus_no: 2 | verbose: yes
    + policy | label_prefix: MCP_9808 | bus_address: 0x18
  + route
    + any-service
      + parent
      + any-child

+ start i2c_mcp9808
  + route
    + service I2c | + child imx8q_evk_i2c | label: MCP_9808
    + any-service | + parent
-
}

build_boot_image [build_artifacts]

run_genode_until forever
