proc wifi_ssid { } {
	return $::env(GENODE_WIFI_SSID)
}

proc wifi_psk { } {
	return $::env(GENODE_WIFI_PSK)
}


proc wifi_wpa { } {
	if {![info exists ::env(GENODE_WIFI_WPA)]} {
		return WPA2
	}
	return $::env(GENODE_WIFI_WPA)
}


create_boot_directory
import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/src/init \
                  [depot_user]/src/libc \
                  [depot_user]/src/openssl \
                  [depot_user]/src/vfs \
                  [depot_user]/raw/[board]-devices \
                  [depot_user]/pkg/imx8mp_qcacld2_wifi

build {
	driver/platform/imx8mp
	driver/pin/imx

	driver/wifi
	lib/imx8mp_qcacld2_wifi
	lib/vfs_jitterentropy

	driver/rtc/dummy
	server/dynamic_rom
	server/nic_router
	server/report_rom
	lib/vfs_lwip
	test/lwip/http_srv
}

#
# wifi config generator (supporting a network list)
#
# You may script your tests with this function in the dynamic_rom config below.
# The syntax for the networks parameter is
#
#   { ssid protection passphrase explicit_scan }
#

set wifi_verbose "no"

proc wifi_config { scan_interval rfkill networks } {
	global wifi_verbose
	global wifi_verbose_state

	append config " | verbose: "       $wifi_verbose \
	              " | scan_interval: " $scan_interval \
	              " | rfkill: "        $rfkill

	set indent "  |     "
	foreach n $networks {
		append config "\n$indent  + network | ssid: "          [lindex $n 0] \
		                                " | protection:"     [lindex $n 1] \
		                                " | passphrase:"     [lindex $n 2] \
		                                " | auto_connect:"   [lindex $n 3] \
		                                " | explicit_scan:"  [lindex $n 4]
	}
	return $config
}

install_config {
config | prio_levels: 2
+ parent-provides
  + service LOG
  + service PD
  + service CPU
  + service ROM
  + service IO_MEM
  + service IRQ

+ default | caps: 100 | ram: 1M

+ start timer
  + route | + any-service | + parent
  + provides | + service Timer

+ start system_report_rom | ram: 2M
  + binary report_rom
  + provides
    + service Report
    + service ROM
  + config | verbose: no
    + default-policy | report: dummy-report
  + route
    + service ROM | + parent
    + service CPU | + parent
    + service PD  | + parent
    + service LOG | + parent
    + service Rtc | + any-child

+ start platform | caps: 150 | ram: 2M | managing_system: yes
  + binary imx8mp_platform
  + provides | + service Platform
  + config
    + policy | label: imx_pio ->           | + device gpio2
    + policy | label: wifi ->  | info: yes | + device usdhc2
  + route
    + service ROM | label: system | + child system_report_rom
    + any-service                 | + parent

+ start imx_pio
  + provides
    + service Pin_state
    + service Pin_control
    + service IRQ
  + config
    + out wlan_vmmc | index: 19 | bank: 0 | default: on
  + route
    + service ROM      | + parent
    + service CPU      | + parent
    + service PD       | + parent
    + service LOG      | + parent
    + service Platform | + child platform

+ start test-lwip_httpsrv | ram: 128M
  + config
  | + libc | stdout: /dev/null | stderr: /dev/log | socket: /socket
  | + vfs
  |   + dir dev
  |   | + log
  |   | + null
  |   + dir socket
  |     + lwip | dhcp: yes
  + route
    + service Nic | + child nic_router
    + any-service
      + parent
      + any-child

+ start nic_router | caps: 150 | ram: 8M
  + provides
  | + service Nic
  | + service Uplink
  + config | verbose: no | verbose_domain_state: yes | dhcp_discover_timeout_sec: 10
  |                                                  | dhcp_request_timeout_sec:  6
  | + policy | label_prefix: test-lwip_httpsrv | domain: downlink
  | + policy | label_prefix: wifi              | domain: uplink
  | + domain uplink | verbose_packets: no | verbose_packet_drop: no | icmp_echo_server: yes
  |   + nat | domain: downlink | tcp-ports: 16384
  |   + tcp-forward | port: 443 | domain: downlink | to: 10.0.3.2
  |   + tcp-forward | port:  80 | domain: downlink | to: 10.0.3.2
  | + domain downlink | verbose_packets: no | verbose_packet_drop: no
  |                   | interface: 10.0.3.1/24
  |   + dhcp-server | ip_first: 10.0.3.2 | ip_last: 10.0.3.2
  + route
    + service ROM   | + parent
    + service CPU   | + parent
    + service PD    | + parent
    + service LOG   | + parent
    + service Timer | + child timer

+ start dummy_rtc
  + provides | + service Rtc
  + config | year: 2023 | month: 02 | day: 27 | hour: 12 | minute: 0 | second: 0
  + route | + any-service | + parent

+ start state_report_rom | ram: 2M
  + binary report_rom
  + provides
    + service Report
    + service ROM
  + config | verbose: no
  + route
    + service ROM | + parent
    + service CPU | + parent
    + service PD  | + parent
    + service LOG | + parent
    + service Rtc | + any-child

+ start accesspoints_report_rom | ram: 2M
  + binary report_rom
  + provides
    + service Report
    + service ROM
  + config | verbose: no
  + route
    + service ROM | + parent
    + service CPU | + parent
    + service PD  | + parent
    + service LOG | + parent
    + service Rtc | + any-child

+ start devices_report_rom | ram: 2M
  + binary report_rom
  + provides
    + service Report
    + service ROM
  + config | verbose: yes
  + route
    + service ROM | + parent
    + service CPU | + parent
    + service PD  | + parent
    + service LOG | + parent
    + service Rtc | + any-child

+ start config_rom | ram: 4M
  + binary dynamic_rom
  + provides | + service ROM
  + config | verbose: yes
  | + rom wifi_config
  |   + inline | description: disconnect
  |     + wifi_config} [wifi_config 15 no {}] {
  |   + sleep  | milliseconds: 15000
  |   + inline | description: connect
  |     + wifi_config} [wifi_config 15 no [list "[wifi_ssid] [wifi_wpa] [wifi_psk] yes no"]] {
  |   + sleep  | milliseconds: 120000
  + route
    + service ROM   | + parent
    + service CPU   | + parent
    + service PD    | + parent
    + service LOG   | + parent
    + service Rtc   | + any-child
    + service Timer | + child timer

+ start wifi | caps: 250 | ram: 32M | priority: -1
  + config | ld_verbose: yes
  | + report | mac_address: true
  | + libc | stdout: /dev/log | stderr: /dev/null | rtc: /dev/rtc | rng: /dev/urandom
  | + vfs
  |   + dir dev
  |     + log
  |     + null
  |     + rtc
  |     + jitterentropy random
  |     + jitterentropy urandom
  |   + dir firmware
  |     + tar wifi_firmware.tar
  + route
    + service Uplink                            | + child nic_router
    + service ROM    | label: wifi.lib.so       | + parent | label: imx8mp_qcacld2_wifi.lib.so
    + service ROM    | label: wifi_firmware.tar | + parent | label: imx8mp_qcacld2_wifi_firmware.tar
    + service ROM    | label: dtb               | + parent | label: wifi-} [board] {.dtb
    + service Report | label: accesspoints      | + child accesspoints_report_rom
    + service Report | label: state             | + child state_report_rom
    + service Report | label: devices           | + child devices_report_rom
    + service ROM    | label: wifi_config       | + child config_rom
    + service ROM                               | + parent
    + service CPU                               | + parent
    + service PD                                | + parent
    + service LOG                               | + parent
    + service Rtc                               | + any-child
    + service Timer                             | + child timer
    + service Platform                          | + child platform
-
}

build_boot_image [list {*}[build_artifacts] wifi-mnt_pocket.dtb]

run_genode_until forever

# vi: set ft=tcl :
