assert {[have_board mnt_pocket]}

create_boot_directory
import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/src/init \
                  [depot_user]/src/imx8mp_platform \
                  [depot_user]/src/stmmac_nic \
                  [depot_user]/src/nic_router \
                  [depot_user]/src/libc \
                  [depot_user]/src/report_rom \
                  [depot_user]/src/vfs \
                  [depot_user]/src/vfs_lwip \
                  [depot_user]/src/init \
                  [depot_user]/raw/[board]-devices

build { test/lwip/http_srv }

install_config {
config
+ parent-provides
  + service ROM
  + service IRQ
  + service IO_MEM
  + service IO_PORT
  + service PD
  + service RM
  + service CPU
  + service LOG

+ default-route
  + any-service
    + parent
    + any-child

+ default | caps: 100 | ram: 1M

+ start timer
  + provides | + service Timer

+ start platform | caps: 150 | ram: 2M | managing_system: yes
  + binary imx8mp_platform
  + provides | + service Platform
  + config
    + policy | label: nic ->  | info: yes | + device eqos
  + route | + any-service | + parent

+ start report_rom | ram: 2M
  + provides
    + service Report
    + service ROM
  + config | verbose: no

+ start nic | caps: 200 | ram: 20M
  + binary stmmac_nic
  + config | mac_address_by_rom: false
  + route
    + service ROM | label: nic.dtb | + parent | label: stmmac_nic-mnt_pocket.dtb
    + service Uplink               | + child nic_router
    + any-service
      + parent
      + any-child

+ start nic_router | caps: 200 | ram: 10M
  + provides
    + service Nic
    + service Uplink
  + config | verbose_domain_state: yes
    + policy | label_prefix: test-lwip_httpsrv | domain: downlink
    + policy | label_prefix: nic | domain: uplink
    + domain uplink
      + nat | domain: downlink | tcp-ports: 16384
      + tcp-forward | port: 443 | domain: downlink | to: 10.0.3.2
      + tcp-forward | port:  80 | domain: downlink | to: 10.0.3.2
    + domain downlink | interface: 10.0.3.1/24
      + dhcp-server | ip_first: 10.0.3.2 | ip_last: 10.0.3.2

+ start test-lwip_httpsrv | caps: 120 | ram: 6M
  + config
  | + vfs
  |   + dir dev    | + log
  |   + dir socket | + lwip | dhcp: yes
  | + libc | stdout: /dev/log | stderr: /dev/log | socket: /socket
  + route
    + service Nic | + child nic_router
    + any-service
      + parent
      + any-child
-
}

# create simple system state ROM
set fd [open [run_dir]/genode/system w]
puts $fd "system | state:\n-"
close $fd

build_boot_image [build_artifacts]
run_genode_until forever
