assert {[have_board mnt_reform2]}

source ${genode_dir}/repos/dde_linux/run/wifi_config.inc

create_boot_directory

import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/src/init \
                  [depot_user]/src/report_rom \
                  [depot_user]/src/rom_filter \
                  [depot_user]/src/dynamic_rom \
                  [depot_user]/src/nic_router \
                  [depot_user]/src/dummy_rtc \
                  [depot_user]/src/imx8mq_platform \
                  [depot_user]/src/imx_pin \
                  [depot_user]/src/imx8mq_pci_host \
                  [depot_user]/pkg/imx8mq_wifi \
                  [depot_user]/raw/mnt_reform2-devices

#
# Build
#

set build_components {
	test/lwip/http_srv
	lib/vfs_jitterentropy
	lib/vfs_lwip
}

build $build_components


#
# Generate config
#

install_config {
config | verbose: yes | prio_levels: 2
+ parent-provides
  + service ROM
  + service IRQ
  + service IO_MEM
  + service IO_PORT
  + service PD
  + service RM
  + service CPU
  + service LOG

+ default-route
  + any-service
    + parent
    + any-child

+ default | caps: 100 | ram: 1M

+ start timer
  + provides
    + service Timer

+ start report_rom | ram: 2M
  + provides
    + service Report
    + service ROM
  + config | verbose: no
    + policy | label: rom_filter -> pci_devices | report: imx8mq_pci_host -> devices

+ start rom_filter | caps: 70
  + provides | + service ROM
  + config | buffer: 32K
  | + input devices
  | + input pci_devices
  | + output | node: devices
  |   + input devices     | skip_toplevel: yes
  |   + input pci_devices | skip_toplevel: yes
  + route
    + service ROM | label: pci_devices | + child report_rom
    + service LOG                      | + parent
    + service PD                       | + parent
    + service CPU                      | + parent
    + service ROM                      | + parent

+ start platform | caps: 300 | ram: 2M | managing_system: yes
  + binary imx8mq_platform
  + provides | + service Platform
  + config
  | + policy | label: gpio -> | info: yes
  |   + device gpio1
  |   + device gpio2
  |   + device gpio3
  |   + device gpio4
  |   + device gpio5
  | + policy | label: imx8mq_pci_host -> | info: yes
  |   + device pcie_1
  |   x device pcie_2
  | + policy | label: wifi -> | info: yes
  |   + pci | class: WIFI
  + route
    + service Report | label: devices | + parent | label: devices
    + service ROM    | label: devices | + child rom_filter
    + service Timer                   | + child timer
    + any-service                     | + parent

+ start gpio | caps: 150 | ram: 2M
  + binary imx_pio
  + provides
    + service Pin_control
    + service Pin_state
    + service IRQ
  + config
    + out pcie0_reset_deassert | bank: 4 | index: 7 | default: on
    + out pcie1_reset_deassert | bank: 2 | index: 23 | default: on
    + policy | label: imx8mq_pci_host ->  | pin: pcie0_reset_deassert
  + route
    + service RM       | + parent
    + service ROM      | + parent
    + service PD       | + parent
    + service CPU      | + parent
    + service LOG      | + parent
    + service Platform | + child platform

+ start imx8mq_pci_host
  + route
    + service RM        | + parent
    + service ROM       | + parent
    + service PD        | + parent
    + service CPU       | + parent
    + service LOG       | + parent
    + service Timer     | + child timer
    + service Report    | + child report_rom
    + service Platform  | + child platform
    + service Pin_state | + child gpio

+ start dummy_rtc
  + provides | + service Rtc
  + config | year: 2023 | month: 01 | day: 19 | hour: 16 | minute: 0 | second: 0
  + route | + any-service | + parent

+ start test-lwip_httpsrv | ram: 128M
  + config
  | + libc | stdout: /dev/null | stderr: /dev/log | socket: /socket
  | + vfs
  |   + dir dev
  |   | + log
  |   | + null
  |   + dir socket
  |     + lwip | dhcp: yes
  + route
    + service Nic
    | + child nic_router
    + any-service
      + parent
      + any-child

+ start state_report_rom | ram: 2M
  + binary report_rom
  + provides
    + service Report
    + service ROM
  + config | verbose: no

+ start accesspoints_report_rom | ram: 2M
  + binary report_rom
  + provides
    + service Report
    + service ROM
  + config | verbose: no

+ start config_rom | ram: 4M
  + binary dynamic_rom
  + provides | + service ROM
  + config | verbose: yes
    + rom wifi_config
      + inline | description: disconnect
} [wifi_config 5 10 no {}] {
      + sleep  | milliseconds: 15000
      + inline | description: connect
} [wifi_config 5 10 no [list "[wifi_ssid] [wifi_wpa] [wifi_psk] no"]] {
      + sleep  | milliseconds: 60000
      + inline | description: rfkill block
} [wifi_config 5 10 yes [list "[wifi_ssid] [wifi_wpa] [wifi_psk] no"]] {
      + sleep  | milliseconds: 30000
      + inline | description: rfkill unblock
} [wifi_config 5 10 no [list "[wifi_ssid] [wifi_wpa] [wifi_psk] no"]] {
      + sleep  | milliseconds: 30000

+ start nic_router | caps: 150 | ram: 8M
  + provides
    + service Nic
    + service Uplink
  + config | verbose: no | verbose_domain_state: yes | dhcp_discover_timeout_sec: 10
                                                       dhcp_request_timeout_sec:  6
    + policy | label_prefix: test-lwip_httpsrv | domain: downlink
    + policy | label_prefix: wifi | domain: uplink
    + domain uplink | verbose_packets: no | verbose_packet_drop: no | icmp_echo_server: yes
      + nat | domain: downlink | tcp-ports: 16384
      + tcp-forward | port: 443 | domain: downlink | to: 10.0.3.2
      + tcp-forward | port:  80 | domain: downlink | to: 10.0.3.2
    + domain downlink | interface: 10.0.3.1/24 | verbose_packets:     no
                                                 verbose_packet_drop: no
      + dhcp-server | ip_first: 10.0.3.2 | ip_last: 10.0.3.2

+ start devices_report_rom | ram: 1200K
  + binary report_rom
  + provides
    + service Report
    + service ROM
  + config | verbose: yes

+ start wifi | caps: 250 | ram: 32M | priority: -1
  + config | ld_verbose: yes
  | + report | mac_address: true
  | + libc | stdout: /dev/log | stderr: /dev/log | rtc: /dev/rtc | rng: /dev/urandom
  | + vfs
  |   + dir dev
  |     + log
  |     + null
  |     + rtc
  |     + jitterentropy random
  |     + jitterentropy urandom
  |   + dir firmware
  |     + tar wifi_firmware.tar
  + route
    + service Uplink                         | + child nic_router
    + service Rtc                            | + any-child
    + service Report | label: accesspoints   | + child accesspoints_report_rom
    + service Report | label: state          | + child state_report_rom
    + service Report | label: devices        | + child devices_report_rom
    + service ROM | label: wifi_config       | + child config_rom
    + service ROM | label: wifi.lib.so       | + parent | label: imx8mq_wifi.lib.so
    + service ROM | label: wifi_firmware.tar | + parent | label: imx8mq_wifi_firmware.tar
    + any-service
      + parent
      + any-child
-
}

build_boot_image [build_artifacts]
run_genode_until forever

# vi: set ft=tcl :
