assert {[have_board mnt_pocket]}

create_boot_directory

import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/src/init \
                  [depot_user]/src/imx8mq_fb \
                  [depot_user]/src/black_hole \
                  [depot_user]/raw/[board]-devices

set build_components {
	driver/framebuffer/imx8mq
	driver/platform/imx8mq
	driver/platform/imx8mp
	test/framebuffer
	driver/pin/imx
}

append_if [have_board mnt_reform2] build_components {
	driver/pin/imx
	driver/i2c/imx8q_evk
	driver/pwm/imx8mq
}

build $build_components

install_config {
config | verbose: yes
+ parent-provides
  + service ROM
  + service IRQ
  + service IO_MEM
  + service IO_PORT
  + service PD
  + service RM
  + service CPU
  + service LOG

+ default-route
  + any-service
    + parent
    + any-child

+ default | caps: 100 | ram: 1M

+ start timer
  + provides | + service Timer

+ start black_hole | ram: 2M
  + provides | + service ROM
  + config | + rom
  + route
    + any-service | + parent

+ start platform | caps: 150 | managing_system: yes
  + binary imx8mp_platform
  + provides | + service Platform
  + config | system_rom: false | verbose: no
  |
  | + policy | label: fb -> | info: yes
  |   + device irqsteer
  |   + device mipi_dsi
  |   + device lcdif1
  |
  | + policy | label: gpio -> | info: yes
  |   + device gpio1
  |   + device gpio2
  |   + device gpio3
  |   + device gpio4
  |   + device gpio5
  + route
    + service ROM | label: system | + child black_hole
    + any-service                 | + parent

+ start gpio | caps: 150 | ram: 2M
  + binary imx_pio
  + provides
    + service Pin_state
    + service Pin_control
    + service IRQ
  + config
    + out panel | index: 7 | bank: 0 | default: on
  + route
    + service RM       | + parent
    + service ROM      | + parent
    + service PD       | + parent
    + service CPU      | + parent
    + service LOG      | + parent
    + service Platform | + child platform

+ start fb | caps: 250 | ram: 128M
  + binary imx8mq_fb
  + route
    + service ROM | label: dtb | + parent | label: } imx8mq_fb-[board].dtb {
    + service RM               | + parent
    + service ROM              | + parent
    + service PD               | + parent
    + service CPU              | + parent
    + service LOG              | + parent
    + service Timer            | + child timer
    + service Platform         | + child platform
    + service Capture          | + child test-framebuffer

+ start test-framebuffer | ram: 10M
  + provides | + service Capture
  + config
-
}

build_boot_image [build_artifacts]

run_genode_until forever
