assert_spec arm_v8a

create_boot_directory
import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/src/imx8mq_platform \
                  [depot_user]/src/imx8mq_sd_card \
                  [depot_user]/src/init \
                  [depot_user]/src/report_rom \
                  [depot_user]/raw/mnt_reform2-devices

build { app/block_tester server/part_block }

install_config {
<config>
	<parent-provides>
		<service name="ROM"/>
		<service name="IRQ"/>
		<service name="IO_MEM"/>
		<service name="PD"/>
		<service name="RM"/>
		<service name="CPU"/>
		<service name="LOG"/>
	</parent-provides>
	<default caps="100"/>

	<start name="imx8mq_platform" ram="2M" managing_system="yes">
		<provides><service name="Platform"/></provides>
		<config>
			<policy label="sd_card -> " info="yes">
				<device name="usdhc1"/>
				<device name="usdhc2"/>
			</policy>
		</config>
		<route>
			<any-service> <parent/> </any-service>
		</route>
	</start>

	<start name="timer" ram="1M">
		<provides><service name="Timer"/></provides>
		<route> <any-service> <parent/> </any-service> </route>
	</start>

	<start name="report_rom" ram="2M">
		<provides> <service name="Report"/> <service name="ROM"/> </provides>
		<config verbose="yes">
		</config>
		<route> <any-service> <parent/> </any-service> </route>
	</start>

	<start name="sd_card" caps="300" ram="16M">
		<binary name="imx8mq_sd_card"/>
		<provides><service name="Block"/></provides>
		<config report="yes">
			<default-policy device="mmcblk1"/>
		</config>
		<route>
			<service name="ROM" label="dtb">
				<parent label="imx8mq_sd_card-mnt_reform2.dtb"/>
			</service>
			<service name="ROM"> <parent/> </service>
			<service name="PD">  <parent/> </service>
			<service name="RM">  <parent/> </service>
			<service name="CPU"> <parent/> </service>
			<service name="LOG"> <parent/> </service>
			<any-service> <any-child/> </any-service>
		</route>
	</start>

	<start name="part_block">
		<binary name="part_block"/>
		<resource name="RAM" quantum="10M"/>
		<provides><service name="Block"/></provides>
		<config>
			<report partitions="yes"/>
			<policy label_prefix="block_tester-1" partition="1" writeable="no"/>
			<policy label_prefix="block_tester-2" partition="1" writeable="no"/>
			<policy label_prefix="block_tester-3" partition="1" writeable="no"/>
			<policy label_prefix="block_tester-4" partition="1" writeable="no"/>
		</config>
		<route>
			<any-service><child name="sd_card"/> <parent/><any-child/></any-service>
		</route>
	</start>

	<start name="block_tester-1" caps="200">
		<binary name="block_tester"/>
		<resource name="RAM" quantum="64M"/>
		<config verbose="no" report="no" log="yes" stop_on_error="no">
			<tests>
				<sequential length="1G" size="4K" batch="128"/>
			</tests>
		</config>
		<route>
			<service name="Block"><child name="part_block"/></service>
			<any-service> <parent/> <any-child /> </any-service>
		</route>
	</start>

	<start name="block_tester-2" caps="200">
		<binary name="block_tester"/>
		<resource name="RAM" quantum="64M"/>
		<config verbose="no" report="no" log="yes" stop_on_error="no">
			<tests>
				<sequential length="1G" size="4K" batch="128"/>
			</tests>
		</config>
		<route>
			<service name="Block"><child name="part_block"/></service>
			<any-service> <parent/> <any-child /> </any-service>
		</route>
	</start>

	<start name="block_tester-3" caps="200">
		<binary name="block_tester"/>
		<resource name="RAM" quantum="64M"/>
		<config verbose="no" report="no" log="yes" stop_on_error="no">
			<tests>
				<sequential length="1G" size="4K" batch="128"/>
			</tests>
		</config>
		<route>
			<service name="Block"><child name="part_block"/></service>
			<any-service> <parent/> <any-child /> </any-service>
		</route>
	</start>

	<start name="block_tester-4" caps="200">
		<binary name="block_tester"/>
		<resource name="RAM" quantum="64M"/>
		<config verbose="no" report="no" log="yes" stop_on_error="no">
			<tests>
				<sequential length="1G" size="4K" batch="128"/>
			</tests>
		</config>
		<route>
			<service name="Block"><child name="part_block"/></service>
			<any-service> <parent/> <any-child /> </any-service>
		</route>
	</start>
</config> }

build_boot_image [build_artifacts]

run_genode_until forever

# vi: set ft=tcl :
