assert {[have_board mnt_pocket]}

create_boot_directory
import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/src/imx8mp_platform \
                  [depot_user]/src/imx8mq_sd_card \
                  [depot_user]/src/init \
                  [depot_user]/src/report_rom \
                  [depot_user]/raw/[board]-devices

build { app/block_tester }

install_config {
config
+ parent-provides
  + service ROM
  + service IRQ
  + service IO_MEM
  + service PD
  + service RM
  + service CPU
  + service LOG

+ default | caps: 100 | ram: 1M

+ start timer
  + provides | + service Timer
  + route | + any-service | + parent

+ start report_rom | ram: 2M
  + provides
    + service Report
    + service ROM
  + config | verbose: no
    + default-policy | report: dummy-report
  + route | + any-service | + parent

+ start imx8mp_platform | ram: 2M | managing_system: yes
  + provides | + service Platform
  + config
  | + policy | label: sd_card ->  | info: yes
  |   + device usdhc1
  |   + device usdhc3
  + route
    + service ROM | label: system | + child report_rom
    + any-service                 | + parent

+ start sd_card | caps: 300 | ram: 16M
  + binary imx8mq_sd_card
  + provides | + service Block
  + config | report: yes
    + default-policy | device: mmcblk0 | . mmcblk0 is the SD-Card, mmcblk1 the eMMC
  + route
    + service ROM | label: dtb | + parent | label: imx8mq_sd_card-mnt_pocket.dtb
    + service ROM              | + parent
    + service PD               | + parent
    + service RM               | + parent
    + service CPU              | + parent
    + service LOG              | + parent
    + any-service              | + any-child

+ start block_tester | ram: 64M
  + config | verbose: no | report: no | log: yes | stop_on_error: no
  | + tests
  |   + sequential | length: 256M | size: 1M | io_buffer: 8M | batch: 4
  |   + sequential | length: 256M | size: 1M | io_buffer: 8M | batch: 4
  |                  start: 2097152 | write: no
  + route
    + service ROM | + parent
    + service PD  | + parent
    + service RM  | + parent
    + service CPU | + parent
    + service LOG | + parent
    + any-service | + any-child
-
}

build_boot_image [build_artifacts]

run_genode_until forever

# vi: set ft=tcl :
