assert {[have_board imx8mp_iot_gate]}

create_boot_directory
import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/src/init \
                  [depot_user]/raw/imx8mp_iot_gate-devices

build {
	driver/usb_hid
	server/event_dump
	server/report_rom
	driver/platform/imx8mp
	driver/usb_host/imx8m
}

install_config {
config | verbose: yes
+ parent-provides
  + service ROM
  + service IRQ
  + service IO_MEM
  + service IO_PORT
  + service PD
  + service RM
  + service CPU
  + service LOG

+ default-route
  + any-service
    + parent
    + any-child

+ default | caps: 100 | ram: 1M

+ start timer
  + provides | + service Timer

+ start report_rom | ram: 2M
  + provides
    + service Report
    + service ROM
  + config | verbose: yes
    + default-policy | report: usb_host -> devices
  + route | + any-service | + parent

+ start platform | caps: 150 | ram: 2M | managing_system: yes
  + binary imx8mp_platform
  + provides | + service Platform
  + config | verbose: yes
  | + policy | label: usb_host ->  | info: yes
  |   + device usb3_phy0
  |   + device usb3_0
  |   + device usb_dwc3_0
  |   + device usb3_phy1
  |   + device usb3_1
  |   + device usb_dwc3_1
  + route
    + service ROM | label: system | + child report_rom
    + any-service                 | + parent

+ start usb_host | caps: 250 | ram: 40M
  + binary imx8m_usb_host
  + provides | + service Usb
  + config
    + policy | label_prefix: usb_hid | + device | class: 0x3
  + route
    + service ROM | label: dtb | + parent | label: imx8m_usb_host-imx8mp_iot_gate.dtb
    + service RM               | + parent
    + service ROM              | + parent
    + service PD               | + parent
    + service CPU              | + parent
    + service LOG              | + parent
    + service Timer            | + child timer
    + service Report           | + child report_rom
    + service Platform         | + child platform

+ start usb_hid | caps: 140 | ram: 11M
  + route
    + service ROM | label: report | + child report_rom
    + service Event               | + child event_dump
    + any-service
      + parent
      + any-child

+ start event_dump
  + provides | + service Event
  + config
  + route
    + any-service
      + parent
      + any-child
-
}

build_boot_image [build_artifacts]

run_genode_until forever
